import type { Metadata } from "next"
import "@/styles/globals.css"
import { routing } from "@/i18n/routing"
import { geistMono, geistSans } from "@/styles/fonts"
import { hasLocale } from "next-intl"
import { getTranslations } from "next-intl/server"
import { notFound } from "next/navigation"

export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: "ru" | "en" }>
}): Promise<Metadata> {
  const { locale } = await params

  const t = await getTranslations({ locale, namespace: "HomePage" })

  if (!hasLocale(routing.locales, locale)) {
    notFound()
  }

  t("description")

  return {
    title: {
      default: "Real U Mobile App",
      template: "%s | Create Next App",
    },
    description: "Generated by create next app",
    icons: {
      icon: "/favicon.ico", // из public/favicon.ico
    },
  }
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode
  params: Promise<{ locale: string }>
}>) {
  const { locale } = await params

  if (!hasLocale(routing.locales, locale)) {
    notFound()
  }

  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
