import type { Metadata } from "next"
import "@/styles/globals.css"
import "lenis/dist/lenis.css"
import { notFound } from "next/navigation"
import { hasLocale, NextIntlClientProvider } from "next-intl"
import { getMessages, getTranslations } from "next-intl/server"

import { routing } from "@/i18n/routing"
import { montserrat } from "@/styles/fonts"

export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> {
  const { locale } = await params
  const t = await getTranslations({ locale: locale as "en" | "ru", namespace: "home-page.meta" })

  if (!hasLocale(routing.locales, locale)) {
    notFound()
  }

  return {
    title: {
      default: t("title"),
      template: "%s | RealU",
    },
    description: "Generated by create next app",
    icons: {
      icon: "/favicon.ico",
    },
  }
}

type Props = {
  children: React.ReactNode
  modal: React.ReactNode
  params: Promise<{ locale: string }>
}

export default async function RootLayout({ children, modal, params }: Props) {
  const { locale } = await params
  const messages = await getMessages({ locale: locale as "en" | "ru" })

  if (!hasLocale(routing.locales, locale)) {
    notFound()
  }

  return (
    <html lang={locale}>
      <body className={`${montserrat.variable} antialiased`}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          {children}
          {modal}
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
